#!/usr/bin/env false

# I don't particularly want to use ZSH anywhere, I am leaving it as my default on macOS. I do
# occasionally get VERY frustrated by how intrusive it is and switch back to Bash to get rid of all
# the extra garbage. When I do so, I don't want Apple telling me I have outstanding tasks... This
# script disables that nanny-message per [this Apple support article](https://support.apple.com/en-us/102360).

export BASH_SILENCE_DEPRECATION_WARNING=1
