#!/usr/bin/env false

# TODO: This is a temporary placeholder for some additional unconditional setup I need to do on my
# Mac. These really need additional refinement to bring up to the rest of my standards but I'm not
# confident I actually need or want these settings:

#export GOPATH="${HOME}/go";
#export PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}";
export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
