ARG NIX_OS_VERSION

FROM docker.io/nixos/nix:${NIX_OS_VERSION}

ADD ./vnix/nix.conf /etc/nix/nix.conf

RUN mkdir -p /workspace && chmod 755 /workspace && chown nobody /workspace
WORKDIR /workspace

#ENV USER=nobody
#ENV NIX_PATH=/nix/var/nix/profiles/per-user/nobody/channels
#ENV PATH=/var/empty/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin

#RUN echo ". /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh" > /home/nixuser/.bashrc && \
#    chown nobody:nobody /home/nixuser/.bashrc

#USER nobody

#ENTRYPOINT ["/nix/var/nix/profiles/default/bin/bash"]
