#!/bin/sh

set -euo pipefail

# An example hook script to verify what is about to be committed. Called by "git commit" with no
# arguments. The hook should exit with non-zero status after issuing an appropriate message if it
# wants to stop the commit.

if git rev-parse --verify HEAD >/dev/null 2>&1; then
  COMMIT_REFERENCE=HEAD
else
  # Initial commit: diff against an empty tree object
  COMMIT_REFERENCE=$(git hash-object -t tree /dev/null)
fi

PRECOMMIT_CHECK_FAILED="false"

# Redirect all output to STDERR
exec 1>&2

# Whitespace at the end of files can be both invisible, as well as problematic not too mention
# generally rude.
function reject_trailing_whitespace() {
  local invalid_filenames="$(git diff-index --check --cached ${COMMIT_REFERENCE} --)"
  local check_result=$?

  if [ ! ${check_result} ]; then
    echo "Precommit Error 001: Found trailing whitespace in the following files:"
    echo "${invalid_filenames}"
    PRECOMMIT_CHECK_FAILED=true
  fi
}

# Cross platform projects tend to avoid non-ASCII filenames, validate they aren't present.
#
# If you want to allow non-ASCII filenames set this variable to true in the specific repository
# where they're needed. The global default I'll use is to err on the side of interoperability.
function reject_nonascii_filenames() {
  local allow_non_ascii=$(git config --type=bool hooks.allownonascii)

  if [ "${allow_non_ascii}" != "true" ]; then
    # This exploits the fact that the printable range starts at the space character and ends with
    # tilde. The use of brackets around a tr range is ok here, (it's even required, for portability
    # to Solaris 10's tr), since the square bracket bytes happen to fall in the designated range.
    local nonascii_char_count=$(git diff --cached --name-only --diff-filter=A -z ${COMMIT_REFERENCE} |
      LC_ALL=C tr -d '[ -~]\0' |
      wc -c |
      awk '{ print $1 }')

    if [ "${nonascii_char_count}" != 0 ]; then
      echo "Precommit Error 002: Found non-ASCII file name in cached changes '${nonascii_char_count}'"
      PRECOMMIT_CHECK_FAILED="true"
    fi
  fi
}

reject_nonascii_filenames
reject_trailing_whitespace

if [ "${PRECOMMIT_CHECK_FAILED}" != "false" ]; then
  echo "Commit rejected due too one or more precommit check failures"
  exit 1
fi
