#!/bin/bash

# To setup the git hooks, please run the dotfile-hook-setup
# or the install script. The install script will
# automagically run this and set it up.

# This script should only be called automatically by from
# within the .git/hooks/ directory. It will trigger any
# local hooks in addition to the hooks that are being
# tracked from within the repository

# It will call the hook based on the name that it was
# called using ($0), through the magic of symlinks the name
# will be different based on the hook called

HOOK=$(basename $0)

# Check if this script was called directly and if it was
# print an error out and exit with an error
if [ "$HOOK" == "hooks-wrapper" ]; then
  echo "This script should only be called through git-hook symlinks"
  echo "Please read the header comment in this file"
  exit 1
fi

echo "Git hook triggered: $HOOK"

# Trigger the local hook if it exists
if [ -x $0.local ]; then
    $0.local "$@" || exit $?
fi

# Trigger the hooks that are stored in the git repository
if [ -x tracked-git-hooks/$HOOK ]; then
    tracked-git-hooks/$HOOK "$@" || exit $?
fi
