#!/bin/bash

# Settings

STORAGE_DIRECTORY="${HOME}/.gitshots"
FSWEBCAM_PATH="$(which fswebcam 2> /dev/null)"

# Don't touch these

BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GIT_DIR_NAME="$(cd ${BASE_DIR}/../..; basename $(pwd))"

if [ -z "${FSWEBCAM_PATH}" ]; then
  # fswebcam isn't available
  exit 0
fi

# Ensure storage directory exists
mkdir -p ${STORAGE_DIRECTORY}

${FSWEBCAM_PATH} -b -q --png -1 -r '712x400' --title "Working in ${GIT_DIR_NAME}" ${STORAGE_DIRECTORY}/$(date +"%Y%m%dT%H%M%S%z").png

