#!/usr/bin/env false

# Environment setup
source "${__SHELL_CFG_ROOT}/common/dotfiles_path.sh.inc"
source "${__SHELL_CFG_ROOT}/common/telemetry_opt_out.sh.inc"
source "${__SHELL_CFG_ROOT}/common/rust_cargo_environment.sh.inc"

# Convenience setup
source "${__SHELL_CFG_ROOT}/common/custom_dictionary.sh.inc"
source "${__SHELL_CFG_ROOT}/common/git_aliases.sh.inc"
source "${__SHELL_CFG_ROOT}/common/password_store.sh.inc"
