#!/usr/bin/env false

if [ -f /etc/zshrc ]; then
  source /etc/zshrc
fi

# The default behavior for zsh is AWFUL around tab completion. The first file is almost always
# wrong in autocompletion and I don't want to have to backspace or cancel back to where I was at to
# get there. Are people actually insane enough to tab through a list of dozens or hundreds of files
# to get to the right one!?
unsetopt MENU_COMPLETE
unsetopt AUTO_MENU
setopt BASH_AUTO_LIST

# Setup my private shell library
__DOTFILE_ROOT="${HOME}/.dotfiles"
source "${__DOTFILE_ROOT}/lib/shim.sh.inc"

__SHELL_CFG_ROOT="${__DOTFILE_ROOT}/configs/shell"

source "${__SHELL_CFG_ROOT}/common.sh.inc"
