#!/usr/bin/env false

if [ -f /etc/zshrc ]; then
  source /etc/zshrc
fi

# Setup my private shell library
__DOTFILE_ROOT="${HOME}/.dotfiles"
source "${__DOTFILE_ROOT}/lib/shim.sh.inc"

__SHELL_CFG_ROOT="${__DOTFILE_ROOT}/configs/shell"

# Common should always precede a specific shell to allow for specific overrides, though
# incompatibilities like that should instead be pulled into the speecific relevant shells instead
# of being overwritten.
source "${__SHELL_CFG_ROOT}/common.sh.inc"

source "${__SHELL_CFG_ROOT}/zsh/shell_prompt.sh.inc"
source "${__SHELL_CFG_ROOT}/zsh/shell_history.sh.inc"
source "${__SHELL_CFG_ROOT}/zsh/disable_aggressive_autocomplete.sh.inc"

if _plc posix_which rbenv >/dev/null 2>&1; then
  eval "$(rbenv init - --no-rehash zsh)"
fi
