[window]
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 5000
multiplier = 5

[font]
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/usr/bin/env"
args = ["bash", "-l"]
