[window]
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 5000
multiplier = 5

[font]
size = 12.0

# Use the standard environment lookup to execute the shell for support of Nix like environments. Need to fix the following, bash hangs without -l, but -l doesn't initialize my whole environment...
#[terminal.shell]
#program = "/usr/bin/env"
#args = ["-S", "bash", "-l"]
